version: "2"
run:
  modules-download-mode: readonly
  tests: true
  allow-parallel-runners: true

linters:
  enable:
    - gosec
    - revive
  settings:
    gosec:
      excludes:
        - G404
      severity: medium
      confidence: medium
    revive:
      confidence: 0.8
      severity: warning
      rules:
        - name: indent-error-flow
        - name: if-return
        - name: var-naming
        - name: unexported-return
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
      - linters:
          - errcheck
          - ineffassign
          - revive
          - staticcheck
        path: \.pb\.go
      - linters:
          - gosec
          - revive
          - staticcheck
        path: (mock|mocks|testdata)/
      - linters:
          - errcheck
          - gosec
          - revive
          - staticcheck
          - ineffassign
        path: test/
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/ma3xco/beacon
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
