// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIWalletManager is a mock of IWalletManager interface.
type MockIWalletManager struct {
	ctrl     *gomock.Controller
	recorder *MockIWalletManagerMockRecorder
}

// MockIWalletManagerMockRecorder is the mock recorder for MockIWalletManager.
type MockIWalletManagerMockRecorder struct {
	mock *MockIWalletManager
}

// NewMockIWalletManager creates a new mock instance.
func NewMockIWalletManager(ctrl *gomock.Controller) *MockIWalletManager {
	mock := &MockIWalletManager{ctrl: ctrl}
	mock.recorder = &MockIWalletManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWalletManager) EXPECT() *MockIWalletManagerMockRecorder {
	return m.recorder
}

// GetBalanceOf mocks base method.
func (m *MockIWalletManager) GetBalanceOf(ctx context.Context, uuid string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceOf", ctx, uuid)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalanceOf indicates an expected call of GetBalanceOf.
func (mr *MockIWalletManagerMockRecorder) GetBalanceOf(ctx, uuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceOf", reflect.TypeOf((*MockIWalletManager)(nil).GetBalanceOf), ctx, uuid)
}

// Transfer mocks base method.
func (m *MockIWalletManager) Transfer(ctx context.Context, fromUUID, toUUID string, amount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transfer", ctx, fromUUID, toUUID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transfer indicates an expected call of Transfer.
func (mr *MockIWalletManagerMockRecorder) Transfer(ctx, fromUUID, toUUID, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transfer", reflect.TypeOf((*MockIWalletManager)(nil).Transfer), ctx, fromUUID, toUUID, amount)
}
